module: MastodonKit
output: docs
author: Ornithologist Coder and MastodonKit Contributors
github_url: https://github.com/MastodonKit/MastodonKit
root_url: https://MastodonKit.github.io/MastodonKit/docs/
docset_icon: icon.png
dash_url: https://MastodonKit.github.io/MastodonKit/docs/docsets/MastodonKit.xml
theme: fullwidth

custom_categories:
  - name: Client
    children:
    - Client
  - name: Resources
    children:
    - Accounts
    - Blocks
    - Clients
    - Favourites
    - FollowRequests
    - Instances
    - Login
    - Media
    - Mutes
    - Notifications
    - Reports
    - Search
    - Statuses
    - Timelines
  - name: Entities
    children:
    - Account
    - Application
    - Attachment
    - Card
    - ClientApplication
    - Context
    - Instance
    - LoginSettings
    - Mention
    - Notification
    - Relationship
    - Report
    - Results
    - Status
    - Tag
